### ISSUE TITLE
Add support for npm (package.json)

### ISSUE THREAD

**Issue by gobwas** [visionmedia/move.js#41]
Am I wrong, or there is no way not to install it via npm?

**Comment by d-oliveros** [comment]
+1

**Comment by axelpale** [comment]
Totally +1. This should be a de facto feature of all modern js libraries. I'm almost frightened to discover move.js is not in npm and does not support CommonJS module definition (easily done with [UMD wrapper](http://davidbcalhoun.com/2014/what-is-amd-commonjs-and-umd/)). Without this it is hard to browserify i.e. build a single app.js file from possibly huge number of required front-end libraries without polluting global namespace. Scandalous!

**Comment by silvenon** [comment]
[Not really](https://github.com/thlorenz/browserify-shim). But it would be nice to have it on npm.

**Comment by axelpale** [comment]
This should be easy. Four of the five dependencies have package.json and are already in NPM:
- [has-translate3d](https://www.npmjs.com/package/has-translate3d)
- [after-transition](https://www.npmjs.com/package/after-transition)
- [component-emitter](https://www.npmjs.com/package/component-emitter)
- [component-query](https://www.npmjs.com/package/component-query)

For the fifth dependency, [css-ease](https://github.com/yields/css-ease), I already created [a pull request providing package.json and the NPM support](https://github.com/yields/css-ease/pull/1).

After that a package.json can be created for Move.js and `npm publish` be run.

There is **one issue** though. Fortunately it is easily solved. The [index.js](https://github.com/visionmedia/move.js/blob/master/index.js) uses `require('emitter')` and `require('query')` instead of `require('component-emitter')` and `require('component-query')` required by NPM. Event they are the same modules, their names are different. In [component.json](https://github.com/visionmedia/move.js/blob/master/component.json) GitHub URLs are used thus enabling the shorter names. **Fortunately** these [same GitHub URLs work in package.json](https://docs.npmjs.com/files/package.json#github-urls) as long as the repos of the URLs have their own package.jsons. Issue solved.

I truly hope that this inclusion of package.json and publishing to NPM is supported by the Move.js community. It is hard to me to see any downsides.

**Comment by silvenon** [comment]
Wow, you were much more helpful :+1:

**Comment by axelpale** [comment]
Pull request incoming. Before that I want mention some additional issues that were on the way.

First, thanks to @yields for [publishing css-ease to npm](https://www.npmjs.com/package/css-ease) with [such a short notice](https://github.com/yields/css-ease/pull/1).

The issue I mentioned in [the previous comment](https://github.com/visionmedia/move.js/issues/41#issuecomment-98548695) turned out harder than first expected. The `require('emitter')` and `require('query')` threw errors about missing modules even when the GitHub URLs were used in package.json. This was understandable because `component-emitter` and `component-query` truly are the identities of the modules, defined in their package.json files, and therefore in spite of many approaches I tried, `npm install` stubbornly included the modules as such.

At first I desperately searched some kind of module aliasing feature in [component.json](https://github.com/componentjs/spec) or [package.json](https://docs.npmjs.com/files/package.json). Of course issue would be solved if `component-emitter` could be aliased with `emitter` and same for `component-query` or vice versa. As it turned out, no aliasing feature exists and for a good reason. It would break some primary design principles of both components and npm modules as discussed by @tj and others in [here](https://github.com/componentjs/component/issues/141), [here](https://github.com/visionmedia/batch/issues/15), [here](https://github.com/npm/npm/issues/2943) and [here](https://groups.google.com/forum/#!topic/commonjs/O2z50Y33N50). The issue suddenly seemed to have very deep roots in the incompatibility between component(1) components and npm modules.

A *try/catch solution* were [hinted by tj](https://github.com/componentjs/component/issues/141#issuecomment-10155449) and [proposed by stephenmathieson](https://github.com/visionmedia/batch/issues/15#issuecomment-30387193) to fix the issue. An ugly one but seemed to be the only option. I tried it and it worked out but while analysing the resulting move.js script, I surprisingly stumbled upon something **much more elegant**: component(1) understood both `require('emitter')` **and** `require('component-emitter')`. For component(1) they both are valid ways to require the component listed as `component/emitter` in the [component.json](https://github.com/visionmedia/move.js/blob/master/component.json). Either `require('emitter')` or `require('component-emitter')`, component(1) translates both to `require('component~emitter@1.2.0')`. Superb.

So no more tries or catches were needed. In the end, the only thing needed for package.json compatibility was to change `require('emitter')` to `require('component-emitter')` and `require('query')` to `require('component-query')`. Both component(1) and browserify understand them; peace has returned to the valley.

**Comment by axelpale** [comment]
The [pull request](https://github.com/visionmedia/move.js/pull/70) has now been submitted and waiting for the merge. Could @yields help us out here, once again? :)

**Comment by lucasmotta** [comment]
Hey @yields - any change of merging this and publishing to npm? :+1:

**Comment by yields** [comment]
i can't maintain this lib anymore :(, don't have time to invest in it ATM (cc @tj)

**Comment by axelpale** [comment]
Finally, [released](https://github.com/visionmedia/move.js/commit/405898d2164fee51ffdd2a0b3f7984e5f42e04e8) to [npm](https://www.npmjs.com/package/move-js) \o/.
